"""Generate placeholder NavSim k-means anchor files so the SparseDrive head can
be constructed before real navtrain anchors are clustered.

Real anchors must be regenerated by running k-means on navtrain trajectories
(see reports/2026_04_29_navsim_setup.md). These placeholders are random and
will not give meaningful predictions; they exist so model construction and
shape-level smoke tests work.
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.environ.get("FORESIGHT_ROOT", "/workspace/ForeSight"))

from mmcv import Config

cfg = Config.fromfile(
    f"{os.environ.get('FORESIGHT_ROOT', '/workspace/ForeSight')}/"
    "projects/configs/sparsedrive_r50_stage2_navsim_planonly.py"
)
fut_mode = cfg.fut_mode
fut_ts = cfg.fut_ts
ego_fut_mode = cfg.ego_fut_mode
ego_fut_ts = cfg.ego_fut_ts
num_driving_cmds = cfg.num_driving_cmds

OUT_DIR = "data/kmeans"
NUM_CLASSES = 10  # nuScenes-style class count; aux supervision ignores nuPlan label set in planning-only

os.makedirs(OUT_DIR, exist_ok=True)

# Motion anchor shape: (num_classes, fut_mode, fut_ts, 2)
motion_path = f"{OUT_DIR}/kmeans_motion_navsim_{fut_mode}.npy"
motion_anchor = np.random.randn(NUM_CLASSES, fut_mode, fut_ts, 2).astype(np.float32) * 0.5
np.save(motion_path, motion_anchor)
print(f"  wrote {motion_path}  shape={motion_anchor.shape}")

# Plan anchor shape: (num_driving_cmds, ego_fut_mode, ego_fut_ts, 2)
plan_path = f"{OUT_DIR}/kmeans_plan_navsim_{ego_fut_mode}_cmd{num_driving_cmds}.npy"
plan_anchor = np.random.randn(num_driving_cmds, ego_fut_mode, ego_fut_ts, 2).astype(np.float32) * 0.5
np.save(plan_path, plan_anchor)
print(f"  wrote {plan_path}  shape={plan_anchor.shape}")
